//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chequeo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chequeo()
        {
            this.Medicacion = new HashSet<Medicacion>();
        }
    
        public int ID { get; set; }
        public int PacienteID { get; set; }
        public int VetID { get; set; }
        public string Prediagnostico { get; set; }
        public double Costo { get; set; }
        public double Peso { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicacion> Medicacion { get; set; }
    }
}
