//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID { get; set; }
        public int PacienteID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Motivo { get; set; }
        public int VetID { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
