//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.Propietarios = new HashSet<PropietarioPaciente>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public string Microchip_Licencia { get; set; }
        public string Genero { get; set; }
        public int RazaID { get; set; }
        public System.DateTime FechaNac { get; set; }
        public System.DateTime FechaIngreso { get; set; }
    
        public virtual Raza Raza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropietarioPaciente> Propietarios { get; set; }
    }
}
