//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropietarioPaciente
    {
        public int ClienteID { get; set; }
        public int PacienteID { get; set; }
        public int Tipo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
