//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropietarioPaciente
    {
        public int ClienteID { get; set; }
        public int PacienteID { get; set; }
        public int Tipo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Propietario Propietario { get; set; }
    }
}
