//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raza
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int EspecieID { get; set; }
    
        public virtual Especie Especie { get; set; }
    }
}
